# site settings
title: Deniz Turkcapar
subtitle: Personal Website
email: dturkcapar@gmail.com
description: Personal website of Deniz Turkcapar
baseurl: "/deniz-turkcapar" # the subpath of your site, e.g. /blog
url: denizturkcapar.github.io # the base hostname & protocol for your site
author: Deniz Turkcapar
city: Chicago
state: IL
zip_code: 50515
country: United States of America

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
